blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/omnitide/control-panel/discussions
    about: Ask questions, share ideas, and discuss general topics related to Omnitide Control Panel
  - name: 📖 Documentation
    url: https://github.com/omnitide/control-panel/blob/main/README.md
    about: Read the comprehensive documentation, guides, and tutorials
  - name: 🔒 Security Vulnerability
    url: https://github.com/omnitide/control-panel/blob/main/SECURITY.md
    about: Please review our Security Policy for reporting vulnerabilities responsibly
  - name: 💼 Commercial Support
    url: mailto:support@omnitide.ai
    about: Enterprise support, consulting, and custom development services
