# LoL Nexus Compute Fabric - Master Configuration
# Trinity Convergence Architecture - Production Ready
[metadata]
name = "LoL Nexus Compute Fabric"
version = "1.0.0"
architecture = "Trinity Convergence"
build_date = "2025-07-25"

[core]
# UMCC Genesis Agent v3.0 Configuration
orchestrator_module = "nexus_orchestrator"
max_concurrent_tasks = 50
execution_timeout = 300
autonomous_mode = true
self_healing = true

[agents]
# PONGEX ExWork Agent v3.0 Integration
exwork_agent_path = "agents/exwork_agent.py"
handler_timeout = 30
max_retries = 3
fallback_mode = "graceful"

[interfaces]
# Unified Interface Configuration
cli_enabled = true
web_enabled = true
tui_enabled = true
natural_language = true

[interfaces.global_commands]
omnimesh_cmd = "interfaces/global_commands/omnimesh"
omni_cmd = "interfaces/global_commands/omni"
om_alias = true

[interfaces.web_frontend]
port = 3000
host = "0.0.0.0"
dev_mode = false
hot_reload = false

[platform]
# Infrastructure Configuration
rust_engine_path = "platform/rust_engine"
go_proxies_path = "core/fabric_proxies"
container_defs_path = "platform/container_defs"
k8s_manifests_path = "platform/k8s_manifests"

[platform.rust_engine]
optimization_level = "release"
target_arch = "x86_64-unknown-linux-gnu"
features = ["grpc", "async", "security"]

[automation]
# GitOps and Deployment Configuration
gitops_engine_path = "automation/gitops_engine"
setup_scripts_path = "automation/setup_scripts"
omnimapper_path = "automation/utils/omnimapper.py"

[automation.gitops]
auto_deploy = true
validation_checks = true
rollback_enabled = true
metrics_collection = true

[security]
# Enhanced Security Configuration
pqc_enabled = false  # Post-Quantum Cryptography placeholder
noa_enabled = false  # Normative-Oblivion Algorithm placeholder
encryption_level = "aes256"
audit_logging = true

[logging]
level = "INFO"
format = "structured"
file_logging = true
log_path = "logs/"
max_file_size = "100MB"
retention_days = 30

[performance]
# Performance Optimization
thread_pool_size = 10
memory_limit = "2GB"
cache_enabled = true
cache_size = "256MB"
compression = true

[development]
# Development and Testing
debug_mode = false
profiling = false
test_mode = false
mock_external_services = false
