// Copied from Phase 1 nexus-prime-core/proto/fabric.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: fabric.proto

package fabricpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- Enums ---
type AgentType int32

const (
	AgentType_AGENT_TYPE_UNSPECIFIED AgentType = 0
	AgentType_AGENT_TYPE_PC          AgentType = 1
	AgentType_AGENT_TYPE_CHROMEBOX   AgentType = 2
	AgentType_AGENT_TYPE_AI_AGENT    AgentType = 3
)

// Enum value maps for AgentType.
var (
	AgentType_name = map[int32]string{
		0: "AGENT_TYPE_UNSPECIFIED",
		1: "AGENT_TYPE_PC",
		2: "AGENT_TYPE_CHROMEBOX",
		3: "AGENT_TYPE_AI_AGENT",
	}
	AgentType_value = map[string]int32{
		"AGENT_TYPE_UNSPECIFIED": 0,
		"AGENT_TYPE_PC":          1,
		"AGENT_TYPE_CHROMEBOX":   2,
		"AGENT_TYPE_AI_AGENT":    3,
	}
)

func (x AgentType) Enum() *AgentType {
	p := new(AgentType)
	*p = x
	return p
}

func (x AgentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentType) Descriptor() protoreflect.EnumDescriptor {
	return file_fabric_proto_enumTypes[0].Descriptor()
}

func (AgentType) Type() protoreflect.EnumType {
	return &file_fabric_proto_enumTypes[0]
}

func (x AgentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentType.Descriptor instead.
func (AgentType) EnumDescriptor() ([]byte, []int) {
	return file_fabric_proto_rawDescGZIP(), []int{0}
}

type StatusType int32

const (
	StatusType_STATUS_TYPE_UNSPECIFIED StatusType = 0
	StatusType_STATUS_TYPE_NODE        StatusType = 1
	StatusType_STATUS_TYPE_AI_AGENT    StatusType = 2
)

// Enum value maps for StatusType.
var (
	StatusType_name = map[int32]string{
		0: "STATUS_TYPE_UNSPECIFIED",
		1: "STATUS_TYPE_NODE",
		2: "STATUS_TYPE_AI_AGENT",
	}
	StatusType_value = map[string]int32{
		"STATUS_TYPE_UNSPECIFIED": 0,
		"STATUS_TYPE_NODE":        1,
		"STATUS_TYPE_AI_AGENT":    2,
	}
)

func (x StatusType) Enum() *StatusType {
	p := new(StatusType)
	*p = x
	return p
}

func (x StatusType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusType) Descriptor() protoreflect.EnumDescriptor {
	return file_fabric_proto_enumTypes[1].Descriptor()
}

func (StatusType) Type() protoreflect.EnumType {
	return &file_fabric_proto_enumTypes[1]
}

func (x StatusType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusType.Descriptor instead.
func (StatusType) EnumDescriptor() ([]byte, []int) {
	return file_fabric_proto_rawDescGZIP(), []int{1}
}

// General response for commands
type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_fabric_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_fabric_proto_rawDescGZIP(), []int{0}
}

func (x *CommandResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CommandResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request to register a new compute node (PC or Chromebox proxy)
type AgentRegistrationRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	IpAddress          string                 `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Capabilities       string                 `protobuf:"bytes,2,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	AgentType          AgentType              `protobuf:"varint,3,opt,name=agent_type,json=agentType,proto3,enum=fabric.AgentType" json:"agent_type,omitempty"`
	ProxyListenAddress string                 `protobuf:"bytes,4,opt,name=proxy_listen_address,json=proxyListenAddress,proto3" json:"proxy_listen_address,omitempty"` // The address (e.g., "127.0.0.1:50052") the proxy is listening on
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AgentRegistrationRequest) Reset() {
	*x = AgentRegistrationRequest{}
	mi := &file_fabric_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRegistrationRequest) ProtoMessage() {}

func (x *AgentRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRegistrationRequest.ProtoReflect.Descriptor instead.
func (*AgentRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_fabric_proto_rawDescGZIP(), []int{1}
}

func (x *AgentRegistrationRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *AgentRegistrationRequest) GetCapabilities() string {
	if x != nil {
		return x.Capabilities
	}
	return ""
}

func (x *AgentRegistrationRequest) GetAgentType() AgentType {
	if x != nil {
		return x.AgentType
	}
	return AgentType_AGENT_TYPE_UNSPECIFIED
}

func (x *AgentRegistrationRequest) GetProxyListenAddress() string {
	if x != nil {
		return x.ProxyListenAddress
	}
	return ""
}

// Response to agent registration
type AgentRegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // Assigned by Nexus Prime
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRegistrationResponse) Reset() {
	*x = AgentRegistrationResponse{}
	mi := &file_fabric_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRegistrationResponse) ProtoMessage() {}

func (x *AgentRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRegistrationResponse.ProtoReflect.Descriptor instead.
func (*AgentRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_fabric_proto_rawDescGZIP(), []int{2}
}

func (x *AgentRegistrationResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AgentRegistrationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentRegistrationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Update message for node or AI agent status
type AgentStatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // ID of the node sending the update
	StatusType    StatusType             `protobuf:"varint,2,opt,name=status_type,json=statusType,proto3,enum=fabric.StatusType" json:"status_type,omitempty"`
	StatusValue   string                 `protobuf:"bytes,3,opt,name=status_value,json=statusValue,proto3" json:"status_value,omitempty"`             // e.g., "Online", "Processing", "Error"
	TelemetryData *TelemetryData         `protobuf:"bytes,4,opt,name=telemetry_data,json=telemetryData,proto3,oneof" json:"telemetry_data,omitempty"` // Detailed metrics (optional)
	CurrentTask   *string                `protobuf:"bytes,5,opt,name=current_task,json=currentTask,proto3,oneof" json:"current_task,omitempty"`       // For AI Agents or nodes with specific tasks
	TaskProgress  *float32               `protobuf:"fixed32,6,opt,name=task_progress,json=taskProgress,proto3,oneof" json:"task_progress,omitempty"`  // 0.0 to 1.0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStatusUpdate) Reset() {
	*x = AgentStatusUpdate{}
	mi := &file_fabric_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatusUpdate) ProtoMessage() {}

func (x *AgentStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatusUpdate.ProtoReflect.Descriptor instead.
func (*AgentStatusUpdate) Descriptor() ([]byte, []int) {
	return file_fabric_proto_rawDescGZIP(), []int{3}
}

func (x *AgentStatusUpdate) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AgentStatusUpdate) GetStatusType() StatusType {
	if x != nil {
		return x.StatusType
	}
	return StatusType_STATUS_TYPE_UNSPECIFIED
}

func (x *AgentStatusUpdate) GetStatusValue() string {
	if x != nil {
		return x.StatusValue
	}
	return ""
}

func (x *AgentStatusUpdate) GetTelemetryData() *TelemetryData {
	if x != nil {
		return x.TelemetryData
	}
	return nil
}

func (x *AgentStatusUpdate) GetCurrentTask() string {
	if x != nil && x.CurrentTask != nil {
		return *x.CurrentTask
	}
	return ""
}

func (x *AgentStatusUpdate) GetTaskProgress() float32 {
	if x != nil && x.TaskProgress != nil {
		return *x.TaskProgress
	}
	return 0
}

// Detailed telemetry data
type TelemetryData struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CpuUtilization    float32                `protobuf:"fixed32,1,opt,name=cpu_utilization,json=cpuUtilization,proto3" json:"cpu_utilization,omitempty"`          // 0.0 to 1.0
	MemoryUtilization float32                `protobuf:"fixed32,2,opt,name=memory_utilization,json=memoryUtilization,proto3" json:"memory_utilization,omitempty"` // 0.0 to 1.0
	NetworkInKbps     float32                `protobuf:"fixed32,3,opt,name=network_in_kbps,json=networkInKbps,proto3" json:"network_in_kbps,omitempty"`
	NetworkOutKbps    float32                `protobuf:"fixed32,4,opt,name=network_out_kbps,json=networkOutKbps,proto3" json:"network_out_kbps,omitempty"` // Add specific sensor data, GPU usage, etc.
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TelemetryData) Reset() {
	*x = TelemetryData{}
	mi := &file_fabric_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryData) ProtoMessage() {}

func (x *TelemetryData) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryData.ProtoReflect.Descriptor instead.
func (*TelemetryData) Descriptor() ([]byte, []int) {
	return file_fabric_proto_rawDescGZIP(), []int{4}
}

func (x *TelemetryData) GetCpuUtilization() float32 {
	if x != nil {
		return x.CpuUtilization
	}
	return 0
}

func (x *TelemetryData) GetMemoryUtilization() float32 {
	if x != nil {
		return x.MemoryUtilization
	}
	return 0
}

func (x *TelemetryData) GetNetworkInKbps() float32 {
	if x != nil {
		return x.NetworkInKbps
	}
	return 0
}

func (x *TelemetryData) GetNetworkOutKbps() float32 {
	if x != nil {
		return x.NetworkOutKbps
	}
	return 0
}

// Fabric-wide events for real-time UI updates
type FabricEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                  // ISO 8601 string
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // e.g., "NODE_ONLINE", "AGENT_TASK_COMPLETED", "SECURITY_ALERT"
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Key-value pairs for context
	Telemetry     *TelemetryData         `protobuf:"bytes,6,opt,name=telemetry,proto3,oneof" json:"telemetry,omitempty"`                                                                   // Event-specific telemetry
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FabricEvent) Reset() {
	*x = FabricEvent{}
	mi := &file_fabric_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FabricEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FabricEvent) ProtoMessage() {}

func (x *FabricEvent) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FabricEvent.ProtoReflect.Descriptor instead.
func (*FabricEvent) Descriptor() ([]byte, []int) {
	return file_fabric_proto_rawDescGZIP(), []int{5}
}

func (x *FabricEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *FabricEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *FabricEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *FabricEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FabricEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *FabricEvent) GetTelemetry() *TelemetryData {
	if x != nil {
		return x.Telemetry
	}
	return nil
}

// Commands issued by the Architect (via UI) to the fabric
type FabricCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	CommandType   string                 `protobuf:"bytes,2,opt,name=command_type,json=commandType,proto3" json:"command_type,omitempty"` // e.g., "DEPLOY_AGENT", "STOP_AGENT", "MIGRATE_AGENT"
	TargetId      string                 `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`          // e.g., Node ID or Agent ID
	Parameters    map[string]string      `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FabricCommand) Reset() {
	*x = FabricCommand{}
	mi := &file_fabric_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FabricCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FabricCommand) ProtoMessage() {}

func (x *FabricCommand) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FabricCommand.ProtoReflect.Descriptor instead.
func (*FabricCommand) Descriptor() ([]byte, []int) {
	return file_fabric_proto_rawDescGZIP(), []int{6}
}

func (x *FabricCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *FabricCommand) GetCommandType() string {
	if x != nil {
		return x.CommandType
	}
	return ""
}

func (x *FabricCommand) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *FabricCommand) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type DeployAgentRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AgentId   string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentType string                 `protobuf:"bytes,2,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"`
	Name      string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Potentially include configuration details or a link to the agent's package
	Parameters    map[string]string `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployAgentRequest) Reset() {
	*x = DeployAgentRequest{}
	mi := &file_fabric_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployAgentRequest) ProtoMessage() {}

func (x *DeployAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployAgentRequest.ProtoReflect.Descriptor instead.
func (*DeployAgentRequest) Descriptor() ([]byte, []int) {
	return file_fabric_proto_rawDescGZIP(), []int{7}
}

func (x *DeployAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *DeployAgentRequest) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *DeployAgentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeployAgentRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type StopAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopAgentRequest) Reset() {
	*x = StopAgentRequest{}
	mi := &file_fabric_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopAgentRequest) ProtoMessage() {}

func (x *StopAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopAgentRequest.ProtoReflect.Descriptor instead.
func (*StopAgentRequest) Descriptor() ([]byte, []int) {
	return file_fabric_proto_rawDescGZIP(), []int{8}
}

func (x *StopAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

var File_fabric_proto protoreflect.FileDescriptor

const file_fabric_proto_rawDesc = "" +
	"\n" +
	"\ffabric.proto\x12\x06fabric\x1a\x1bgoogle/protobuf/empty.proto\"C\n" +
	"\x0fCommandResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc1\x01\n" +
	"\x18AgentRegistrationRequest\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x01 \x01(\tR\tipAddress\x12\"\n" +
	"\fcapabilities\x18\x02 \x01(\tR\fcapabilities\x120\n" +
	"\n" +
	"agent_type\x18\x03 \x01(\x0e2\x11.fabric.AgentTypeR\tagentType\x120\n" +
	"\x14proxy_listen_address\x18\x04 \x01(\tR\x12proxyListenAddress\"f\n" +
	"\x19AgentRegistrationResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xcf\x02\n" +
	"\x11AgentStatusUpdate\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x123\n" +
	"\vstatus_type\x18\x02 \x01(\x0e2\x12.fabric.StatusTypeR\n" +
	"statusType\x12!\n" +
	"\fstatus_value\x18\x03 \x01(\tR\vstatusValue\x12A\n" +
	"\x0etelemetry_data\x18\x04 \x01(\v2\x15.fabric.TelemetryDataH\x00R\rtelemetryData\x88\x01\x01\x12&\n" +
	"\fcurrent_task\x18\x05 \x01(\tH\x01R\vcurrentTask\x88\x01\x01\x12(\n" +
	"\rtask_progress\x18\x06 \x01(\x02H\x02R\ftaskProgress\x88\x01\x01B\x11\n" +
	"\x0f_telemetry_dataB\x0f\n" +
	"\r_current_taskB\x10\n" +
	"\x0e_task_progress\"\xb9\x01\n" +
	"\rTelemetryData\x12'\n" +
	"\x0fcpu_utilization\x18\x01 \x01(\x02R\x0ecpuUtilization\x12-\n" +
	"\x12memory_utilization\x18\x02 \x01(\x02R\x11memoryUtilization\x12&\n" +
	"\x0fnetwork_in_kbps\x18\x03 \x01(\x02R\rnetworkInKbps\x12(\n" +
	"\x10network_out_kbps\x18\x04 \x01(\x02R\x0enetworkOutKbps\"\xc3\x02\n" +
	"\vFabricEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12=\n" +
	"\bmetadata\x18\x05 \x03(\v2!.fabric.FabricEvent.MetadataEntryR\bmetadata\x128\n" +
	"\ttelemetry\x18\x06 \x01(\v2\x15.fabric.TelemetryDataH\x00R\ttelemetry\x88\x01\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\f\n" +
	"\n" +
	"_telemetry\"\xf4\x01\n" +
	"\rFabricCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12!\n" +
	"\fcommand_type\x18\x02 \x01(\tR\vcommandType\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\x12E\n" +
	"\n" +
	"parameters\x18\x04 \x03(\v2%.fabric.FabricCommand.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xed\x01\n" +
	"\x12DeployAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x02 \x01(\tR\tagentType\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12J\n" +
	"\n" +
	"parameters\x18\x04 \x03(\v2*.fabric.DeployAgentRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"-\n" +
	"\x10StopAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId*m\n" +
	"\tAgentType\x12\x1a\n" +
	"\x16AGENT_TYPE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rAGENT_TYPE_PC\x10\x01\x12\x18\n" +
	"\x14AGENT_TYPE_CHROMEBOX\x10\x02\x12\x17\n" +
	"\x13AGENT_TYPE_AI_AGENT\x10\x03*Y\n" +
	"\n" +
	"StatusType\x12\x1b\n" +
	"\x17STATUS_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10STATUS_TYPE_NODE\x10\x01\x12\x18\n" +
	"\x14STATUS_TYPE_AI_AGENT\x10\x022\xb8\x02\n" +
	"\rFabricService\x12T\n" +
	"\rRegisterAgent\x12 .fabric.AgentRegistrationRequest\x1a!.fabric.AgentRegistrationResponse\x12G\n" +
	"\x11UpdateAgentStatus\x12\x19.fabric.AgentStatusUpdate\x1a\x17.fabric.CommandResponse\x12C\n" +
	"\x12StreamFabricEvents\x12\x16.google.protobuf.Empty\x1a\x13.fabric.FabricEvent0\x01\x12C\n" +
	"\x11SendFabricCommand\x12\x15.fabric.FabricCommand\x1a\x17.fabric.CommandResponse2\x96\x01\n" +
	"\x10NodeProxyService\x12B\n" +
	"\vDeployAgent\x12\x1a.fabric.DeployAgentRequest\x1a\x17.fabric.CommandResponse\x12>\n" +
	"\tStopAgent\x12\x18.fabric.StopAgentRequest\x1a\x17.fabric.CommandResponseB7Z5github.com/omnimesh/go-node-proxies/internal/fabricpbb\x06proto3"

var (
	file_fabric_proto_rawDescOnce sync.Once
	file_fabric_proto_rawDescData []byte
)

func file_fabric_proto_rawDescGZIP() []byte {
	file_fabric_proto_rawDescOnce.Do(func() {
		file_fabric_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fabric_proto_rawDesc), len(file_fabric_proto_rawDesc)))
	})
	return file_fabric_proto_rawDescData
}

var file_fabric_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_fabric_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_fabric_proto_goTypes = []any{
	(AgentType)(0),                    // 0: fabric.AgentType
	(StatusType)(0),                   // 1: fabric.StatusType
	(*CommandResponse)(nil),           // 2: fabric.CommandResponse
	(*AgentRegistrationRequest)(nil),  // 3: fabric.AgentRegistrationRequest
	(*AgentRegistrationResponse)(nil), // 4: fabric.AgentRegistrationResponse
	(*AgentStatusUpdate)(nil),         // 5: fabric.AgentStatusUpdate
	(*TelemetryData)(nil),             // 6: fabric.TelemetryData
	(*FabricEvent)(nil),               // 7: fabric.FabricEvent
	(*FabricCommand)(nil),             // 8: fabric.FabricCommand
	(*DeployAgentRequest)(nil),        // 9: fabric.DeployAgentRequest
	(*StopAgentRequest)(nil),          // 10: fabric.StopAgentRequest
	nil,                               // 11: fabric.FabricEvent.MetadataEntry
	nil,                               // 12: fabric.FabricCommand.ParametersEntry
	nil,                               // 13: fabric.DeployAgentRequest.ParametersEntry
	(*emptypb.Empty)(nil),             // 14: google.protobuf.Empty
}
var file_fabric_proto_depIdxs = []int32{
	0,  // 0: fabric.AgentRegistrationRequest.agent_type:type_name -> fabric.AgentType
	1,  // 1: fabric.AgentStatusUpdate.status_type:type_name -> fabric.StatusType
	6,  // 2: fabric.AgentStatusUpdate.telemetry_data:type_name -> fabric.TelemetryData
	11, // 3: fabric.FabricEvent.metadata:type_name -> fabric.FabricEvent.MetadataEntry
	6,  // 4: fabric.FabricEvent.telemetry:type_name -> fabric.TelemetryData
	12, // 5: fabric.FabricCommand.parameters:type_name -> fabric.FabricCommand.ParametersEntry
	13, // 6: fabric.DeployAgentRequest.parameters:type_name -> fabric.DeployAgentRequest.ParametersEntry
	3,  // 7: fabric.FabricService.RegisterAgent:input_type -> fabric.AgentRegistrationRequest
	5,  // 8: fabric.FabricService.UpdateAgentStatus:input_type -> fabric.AgentStatusUpdate
	14, // 9: fabric.FabricService.StreamFabricEvents:input_type -> google.protobuf.Empty
	8,  // 10: fabric.FabricService.SendFabricCommand:input_type -> fabric.FabricCommand
	9,  // 11: fabric.NodeProxyService.DeployAgent:input_type -> fabric.DeployAgentRequest
	10, // 12: fabric.NodeProxyService.StopAgent:input_type -> fabric.StopAgentRequest
	4,  // 13: fabric.FabricService.RegisterAgent:output_type -> fabric.AgentRegistrationResponse
	2,  // 14: fabric.FabricService.UpdateAgentStatus:output_type -> fabric.CommandResponse
	7,  // 15: fabric.FabricService.StreamFabricEvents:output_type -> fabric.FabricEvent
	2,  // 16: fabric.FabricService.SendFabricCommand:output_type -> fabric.CommandResponse
	2,  // 17: fabric.NodeProxyService.DeployAgent:output_type -> fabric.CommandResponse
	2,  // 18: fabric.NodeProxyService.StopAgent:output_type -> fabric.CommandResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_fabric_proto_init() }
func file_fabric_proto_init() {
	if File_fabric_proto != nil {
		return
	}
	file_fabric_proto_msgTypes[3].OneofWrappers = []any{}
	file_fabric_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fabric_proto_rawDesc), len(file_fabric_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_fabric_proto_goTypes,
		DependencyIndexes: file_fabric_proto_depIdxs,
		EnumInfos:         file_fabric_proto_enumTypes,
		MessageInfos:      file_fabric_proto_msgTypes,
	}.Build()
	File_fabric_proto = out.File
	file_fabric_proto_goTypes = nil
	file_fabric_proto_depIdxs = nil
}
