name: Docker Build CI

on:
  push:
    paths:
      - 'go-node-proxies/**'
  pull_request:
    paths:
      - 'go-node-proxies/**'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go-node-proxies
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub (optional)
        if: ${{ secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        run: docker build -t omnimesh/gcnp:ci .
      - name: Run container smoke test
        run: docker run --rm omnimesh/gcnp:ci --help || true
