apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: omnitide-base

resources:
- nexus-prime-core.yaml
- go-node-proxy.yaml
- secrets.yaml
- configmap.yaml

commonLabels:
  app.kubernetes.io/name: omnitide
  app.kubernetes.io/part-of: omnitide-compute-fabric

images:
- name: gcr.io/PROJECT_ID/nexus-prime-core
  newTag: latest
- name: gcr.io/PROJECT_ID/go-node-proxy
  newTag: latest
