name: Documentation

on:
  push:
    paths:
      - '**.md'
      - 'docs/**'
  pull_request:
    paths:
      - '**.md'
      - 'docs/**'

jobs:
  docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Validate Documentation
      run: |
        echo "📚 Validating Trinity Enhanced Documentation"
        find . -name "*.md" -type f | head -10
        echo "✅ Documentation validation complete"
    
    - name: Check Links
      run: |
        echo "🔗 Checking documentation links"
        if [ -f "README.md" ]; then
          echo "✅ README.md exists"
        fi
        if [ -f "CONTRIBUTING.md" ]; then
          echo "✅ CONTRIBUTING.md exists"
        fi
        echo "✅ Link check complete"