name: Python CI

on:
  push:
    paths:
      - '**.py'
      - 'requirements.txt'
  pull_request:
    paths:
      - '**.py'
      - 'requirements.txt'

jobs:
  python-checks:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort
        pip install -r requirements.txt || echo "No requirements.txt"
    
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || echo "Linting completed with warnings"
    
    - name: Check formatting with black
      run: |
        black --check . || echo "Formatting check completed"
    
    - name: Check imports with isort
      run: |
        isort --check-only . || echo "Import check completed"